### ISSUE TITLE
Add ability to not keep exiftool running (remove -stay_open)

### ISSUE THREAD

**Issue by AndyDragon** [coenm/AsyncExifTool#39]
It seems that the -stay_open flag causes the task for ExecuteAsync() to never exit when using .NET Core on macOS.  Works fine on .NET Core on Windows.  Haven't tested Linux.

**Comment by AndyDragon** [comment]
Actually, looking through the code, this would not be possible, it would completely change the way the code works.

**Comment by coenm** [comment]
@AndyDragon  I've not tested it on a Mac but i'm interested in what is going wrong.

You can create the AsyncExifTool with a logger instance. Then all the commands to exiftool and the stdout and stderr are logged. 

See  tests/Samples/AsyncExifToolToNLogAdapter.cs for an example logger. 

Please also use the latest (beta) release on nuget.org as it contain a small bugfix

**Comment by AndyDragon** [comment]
I created a simple console logger and this is what I am seeing:

```
Using default options, user options not found
** LOG: Info : Initializing
** LOG: Trace : Added shells ProcessExited event handler.
** LOG: Trace : Start initialising shell
** LOG: Info : Initialized
Processing /Volumes/DragonNAS/Photography/Digital/Family/Nikon Z7/DCIM/102NIKZ7/DSC_0007.NEF...
** LOG: Debug : ExecuteAsync - Wait before entering executeAsyncSyncLock.
** LOG: Debug : ExecuteAsync - Entered executeAsyncSyncLock.
** LOG: Trace : WriteLineAsync: -a
** LOG: Trace : WriteLineAsync: -g
** LOG: Trace : WriteLineAsync: -sort
** LOG: Trace : WriteLineAsync: /Volumes/DragonNAS/Photography/Digital/Family/Nikon Z7/DCIM/102NIKZ7/DSC_0007.NEF
** LOG: Trace : WriteLineAsync: -execute1
```

Entries being logged start with '** LOG'

**Comment by AndyDragon** [comment]
Is it possible that the image needs to be wrapped in quotes?

**Comment by AndyDragon** [comment]
When I ran this locally:

```
exiftool -stay_open True -@ ./argfiletest
```

The tool ran fine.  'argfiletest' looked like this (LF or CRLF line endings, both worked):

```
-a
-g
-sort
/Volumes/DragonNAS/Photography/Digital/Family/Nikon Z7/DCIM/102NIKZ7/DSC_0007.NEF
-execute1
```

**Comment by AndyDragon** [comment]
BTW, the code I am working on can be found here: https://github.com/AndyDragon/ImageDetailsCataloger

It is a dotnet core console application that pulls the exiftool data and adds it all to a SQLite DB.  Works on Windows CMD prompt, freezes randomly on GIT bash for Windows and every single time on bash for Mac.

**Comment by coenm** [comment]
I've opened a pullrequest for your repo. I'm not able to test is but i believe the problem is the newline character you have to specify in the AsyncExifToolConfiguration. This will probably change in the future.

Let me know if this fixes your problem.

**Comment by AndyDragon** [comment]
That worked, once the newline was set to the environment, it worked.  Thank you!
