### ISSUE TITLE
exifToolFullFilename cannot contain space

### ISSUE THREAD

**Issue by VTol-zz** [coenm/AsyncExifTool#46]
In the AsyncExifToolConfiguration constructor, the exifToolFullFilename value cannot contain space. Else the AsyncExifToolInitialisationException exception (Could not initialise exiftool/The system cannot find the file specified) is thrown.

**Comment by coenm** [comment]
Thank you for your bug report. I will look into this in the next version but to be honest, there isn't any planned yet.

Feel free to fix the bug and create a pull request. Otherwise, make sure the full path doesn't contain any spaces.
